# Generated by Django 2.2.8 on 2020-08-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(default='--/--/--')),
                ('image', models.ImageField(default='image', upload_to='')),
                ('audio', models.FileField(default='audio', upload_to='')),
            ],
        ),
    ]
