# Generated by Django 3.1 on 2020-08-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_track_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='program title')),
                ('prg_date', models.DateField(default='--/--/--')),
            ],
        ),
    ]
