# Generated by Django 3.1 on 2020-08-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='prg_date',
            new_name='program_date',
        ),
        migrations.RemoveField(
            model_name='track',
            name='description',
        ),
    ]
