# Generated by Django 3.1 on 2020-08-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200811_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='program_location',
            field=models.TextField(default='city/place'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='program title', max_length=100),
        ),
    ]
