# Generated by Django 3.1 on 2020-08-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200811_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='program description', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='program_location',
            field=models.CharField(default='city/place', max_length=100),
        ),
    ]
