# Generated by Django 3.1 on 2020-08-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200811_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_image',
            name='image',
            field=models.ImageField(default='image', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(default='audio', upload_to='Tracks/audio/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(default='image', upload_to='Tracks/'),
        ),
    ]
