# Generated by Django 3.1 on 2020-08-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200811_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(default='image', upload_to='Tracks/images/'),
        ),
    ]
